name: Discord Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install aiohttp python-dotenv gspread google-auth
      
    - name: Create .env file from secrets
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
        echo "CHANNEL_URLS=${{ secrets.CHANNEL_URLS }}" >> .env
        echo "MAX_MESSAGES=500" >> .env
        echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
        # Create a separate file for Google credentials (not in .env)
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > google_credentials.json
        cat google_credentials.json | head -c 100  # Debug: show first 100 chars
      
    - name: Run scraper
      run: python discord_scraper_gsheets.py